--USE BTLon;

CREATE TABLE CUDAN
(
  MaCD NVARCHAR(5) NOT NULL PRIMARY KEY,
  HoTen NVARCHAR(30) NOT NULL,
  SDT INT NOT NULL,
  Email NVARCHAR(30) NOT NULL,
  SoCC VARCHAR(12) NOT NULL,
  DaiDien BIT NOT NULL,
  QueQuan NVARCHAR(30) NOT NULL,
  NamSinh DATETIME NOT NULL
);

CREATE TABLE CANHO
(
  MaCH NVARCHAR(5) NOT NULL PRIMARY KEY,
  DienTich NVARCHAR(5) NOT NULL,
  LoaiHinh NVARCHAR(15) NOT NULL,
  TinhTrang NVARCHAR(30) NOT NULL,
  GiaThue INT NOT NULL,
  TienCoc INT NOT NULL
);

CREATE TABLE HOADON
(
  SoHD INT NOT NULL PRIMARY KEY,
  TongTien INT NOT NULL,
  HanTT DATETIME NOT NULL,
  TinhTrangHD NVARCHAR(30) NOT NULL,
  MaCH NVARCHAR(5) NOT NULL,
  FOREIGN KEY (MaCH) REFERENCES CANHO(MaCH)
);

CREATE TABLE DICHVU
(
  MaDV NVARCHAR(5) NOT NULL PRIMARY KEY,
  TenDV INT NOT NULL,
  DonGia INT NOT NULL
);

CREATE TABLE CHITIETHD
(
  MaDV NVARCHAR(5) NOT NULL,
  SoHD INT NOT NULL,
  SoLuong INT,
  CONSTRAINT pk_chitiethd PRIMARY KEY (MaDV, SoHD),
  FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV),
  FOREIGN KEY (SoHD) REFERENCES HOADON(SoHD)
);

CREATE TABLE HOPDONG
(
  MaHD INT NOT NULL PRIMARY KEY,
  MaCH NVARCHAR(5) NOT NULL,
  TinhTrangHD NVARCHAR(30) NOT NULL,
  NgayBD DATETIME NOT NULL,
  NgayKT DATETIME NOT NULL,
  FOREIGN KEY (MaCH) REFERENCES CANHO(MaCH)
);

CREATE TABLE THOATHUAN
(
  NgayGH DATETIME NOT NULL,
  MaHD INT NOT NULL,
  MaCD NVARCHAR(5) NOT NULL,
  CONSTRAINT pk_thoathuan PRIMARY KEY (MaHD, MaCD),
  FOREIGN KEY (MaHD) REFERENCES HOPDONG(MaHD),
  FOREIGN KEY (MaCD) REFERENCES CUDAN(MaCD)
);